name: Bug Report
description: Report something that isn't working
labels: ["bug"]
body:
  - type: input
    id: app-version
    attributes:
      label: App Version
      placeholder: "e.g. 1.0.0"
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android Version
      placeholder: "e.g. Android 14"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: "e.g. Pixel 7, Samsung S24"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Tap on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should have happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
    validations:
      required: false
