name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
    validations:
      required: true
